import { FC, ReactNode } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "./MainLayout.module.css";
import Navbar from "../Navbar";

type Props = {
  children: ReactNode;
};

const inter = Inter({ subsets: ["latin"] });

export const MainLayout: FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>About - Marcos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`${styles.main} ${inter.className}`}>{children}</main>
    </>
  );
};
